### ISSUE TITLE
incorrect connection URL to vrops API

### ISSUE THREAD

**Issue by IvanTheFirst** [kovarus/vrealize-pysdk#7]
I don't know which version of vRealize you using, but I get 404 error on 'https://' + cloudurl + '/identity/api/tokens'. So I add some IF to your code (classes.py) from 115 line:
```
            if str(r).find('404') != -1:
                r = requests.post(
                    url='https://' + cloudurl + '/suite-api/api/auth/token/acquire',
                    headers={'Content-type': 'Application/json',
                             'Accept': 'Application/json'},
                    verify=ssl_verify,
                    data=json.dumps({
                        "tenant": tenant,
                        "username": username,
                        "password": password
                    })
                )
```

**Comment by russellpope** [comment]
It should be tested up to vRealize Automation 7.4. I'll update the description to make it more clear this is for vRealize Automation not vRealize Operations. I think that's the auth URL you're trying to go for. Could you confirm?

In the mean time check out this: https://blogs.vmware.com/management/2016/02/straight-up-flying-with-the-vrealize-operations-rest-api.html 

You should find a link to a python vrops client library in the docs. If it's not what you're looking for let me know and I can start to wrap the vRops API.

**Comment by IvanTheFirst** [comment]
Yes, It was my mistake, I'm sorry. I try to connect to vRealize Operation Manager. Thank you for your link, you helped me a lot!
